#!/bin/sh
# Absolute path
ROO_HOME=/Users/mduduzikeswa/Documents/dev/mazasoft/projects/tako-libraries/cnf
echo "Resolved ROO_HOME: $ROO_HOME"
ROO_CNF_HOME=/Users/mduduzikeswa/Documents/dev/mazasoft/projects/tako/cnf.OLD
echo "Resolved ROO_CNF_HOME: $ROO_CNF_HOME"
ROO_HOME_PARENT=/Users/mduduzikeswa/Documents/dev/mazasoft/projects/tako
echo "Resolved ROO_HOME_PARENT: $ROO_HOME_PARENT"

# Remove osgi cache
rm -rf "$ROO_HOME"/lib/deps

mkdir -p "$ROO_HOME"/lib/deps


# Most Roo bundles are not special and belong in "bundle"
# Copy Addon bundles
# Copy Runtime Bundles
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.scr-2.0.14.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/slf4j.api-1.7.21.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/slf4j.jdk14-1.7.21.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.commons.codec-1.8.0.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.commons.io-2.4.0.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.commons.lang3-3.1.0.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.fusesource.jansi-1.6.0.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.jsoup-1.9.1.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.bundlerepository-2.0.8.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.configadmin-1.8.10.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.coordinator-1.0.0.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.eventadmin-1.4.8.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.gogo.command-0.16.0.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.gogo.runtime-0.16.2.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.log-1.0.1.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.felix.metatype-1.1.2.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.servicemix.bundles.freemarker-2.3.23.1.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.aries.subsystem.api-2.0.8.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.aries.util-1.1.1.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.apache.aries.subsystem.core-2.0.8.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/org.eclipse.equinox.region-1.1.0.v20120522-1841.jar "$ROO_HOME"/lib/deps
cp "$ROO_CNF_HOME"/cache/3.5.0/Amdatu Blueprint OSGi/com.github.antlrjavaparser.antlr-java-parser-1.0.15.jar "$ROO_HOME"/lib/deps

cp "$ROO_HOME_PARENT"/org.tako.libraries/generated/org.tako.wrapped.bcpg-jdk15-1.45.10.201805310100.jar "$ROO_HOME"/lib/deps
cp "$ROO_HOME_PARENT"/org.tako.libraries/generated/org.tako.wrapped.bcprov-jdk15-1.45.10.201805310100.jar "$ROO_HOME"/lib/deps
cp "$ROO_HOME_PARENT"/org.tako.libraries/generated/org.tako.wrapped.jline-1.0.0.S2-B0013.jar "$ROO_HOME"/lib/deps
cp "$ROO_HOME_PARENT"/org.tako.libraries/generated/org.tako.wrapped.json-simple-1.1.10.201805310100.jar "$ROO_HOME"/lib/deps
cp "$ROO_HOME_PARENT"/org.tako.libraries/generated/org.tako.libraries.antlr4-runtime.jar "$ROO_HOME"/lib/deps